version: '3'

services:
  speedtest-monitoring:
    image: ghcr.io/gustoliveira/speedtest-monitoring:latest
    container_name: speedtest-monitoring
    environment:
      - TIMEZONE=America/Sao_Paulo
      - TEST_PERIOD_MIN=30
