version: '3'

services:
  speedtest-monitoring:
    image: gustoliveira/speedtest-monitoring:0.1
    container_name: speedtest-monitoring
    environment:
      - TIMEZONE=America/Sao_Paulo
      - TEST_PERIOD_MIN=30
